### ISSUE TITLE
forwarder: implement PIT timeout

### ISSUE THREAD

**Issue by RoySCU** [named-data-iot/ndn-lite#11]
Currently, PIT entries never expire and timeout callbacks are never be triggered.

**Comment by zjkmxy** [comment]
Do you have any ideas on this? I think the way we time may differ with platforms. Maybe we need a timer module with different backends?

**Comment by RoySCU** [comment]
I share the same idea with you. Maybe we should organize the timer module like security (i.e. to have _abstract_timer)._ But different platforms' timer interfaces may vary greatly. Therefore defining frontend interfaces is not a easy task. nRF52840 might be a good start and I'm close to finish a nRF5 SDK15 backend (a simple wrapper but not a good design). It seems we should create a _timer_ branch before nailing down _timer-frontend_ details.

**Comment by RoySCU** [comment]
Hi guys, the new _timer_ branch provides basic timer support of nRF52840 via a [nRF5 SDK15.2.0](https://www.nordicsemi.com/DocLib/Content/SDK_Doc/nRF5_SDK/v15-2-0/group__app__timer) wrapper. You can try this by the [test project](https://github.com/RoySCU/ndn-lite-timer-test), but you need to deal with the preprocessor before building it. May this [guide](https://drive.google.com/file/d/1mZEiv9JIDn57H9chCPhR2HgvpES6qa8M/view) can help you.

**Comment by yoursunny** [comment]
I’m looking at `ndn-lite-timer.h` API as of e0d7d479b4ab7cd815e7336902176e73cdf63030. It lacks Doxygen on backend side, so I can only guess its semantics.

The design depends on a **real time clock (RTC)** module. This is fine, as most platforms have some sort of RTC.
The design requires exclusive control of the RTC through `ndn_timer_backend_t.rtc_pause` function. This is problematic because there are only a handful of RTC available.

The design places the responsibility of managing multiple timers to the backend. This part is platform independent and should be moved to the frontend.

It is unclear what thread/task the `ndn_timer_timeout` callback should be executed. Depending on backend implementation, it’ll probably be in a different thread/task than the thread/task that scheduled the event, or even in an interrupt service routine (ISR). Invoking the callback in a different thread/task could cause thread safety issues; invoking the callback in an ISR has even more problems.
Commonly in FreeRTOS, the ISR sends a message to a queue, and the main task receives the message and trigger the timer callback, but the design does not allow a way to invoke timer callback in the main task.

The easiest way to implement this timer is providing two functions from backend:

* **millis** tells the current time in milliseconds.
* **delay** yields the current thread/task for a specified duration.

See Arduino cores of each platform for how they are implemented.
The rest can be done in the frontend implementation:

1. Compute when a timer would expire in terms of `millis()`.
2. Organize timers in a priority queue (i.e. heap) according to their expiration time.
3. `delay` until the earliest expiration occurs. If you use same thread/task to deal with network and timers, just `delay(0)` then check the sockets and the first timer.

**Comment by RoySCU** [comment]
Yes, the current timer is problematic and just a quick work to prove the idea of timer abstraction. If we need a more effective and safe design.

- Perhaps we should remove `ndn_timer_backend_t.rtc_pause`  `ndn_timer_backend_t.rtc_resume` and keep the timer responsibility simple.
- Agree with you on managing multiple timers in frontend instead on backend.
- Providing **millis** and **delay** from backend would be nice, and I notice many platform agnostic libraries do in similar ways. Will look into Arduino cores to see how they do adaptation for nRF52840. 

Thanks for your suggestions. I'll re-implement the timer by your advice.

**Comment by yoursunny** [comment]
To be clear, **millis** and **delay** would be the ONLY functions provided by the backend. There are no other functions providing direct access to RTC. Arduino also has **micros** and **delayMicroseconds** but I doubt NDN stack would need microsecond-level timer accuracy.

nRF52840 does not have Arduino core, but nRF52832 has https://github.com/adafruit/Adafruit_nRF52_Arduino .
FreeRTOS does not have a function equivalent to **millis**, but it can be approached by returning a counter that is periodically incremented in an ISR triggered by RTC.

**Comment by Zhiyi-Zhang** [comment]
I agree with Junxiao.
Let's develop an event_queue (let's make it under `./forwarder`) in the ndn-lite and expose the API for event/callback register.

NDN-Lite can also provide a function to start the loop.

**Comment by zjkmxy** [comment]
So how do we implement the event_queue? Should we ensure it to be thread-safe? If so, maybe it relies on some platform-specific function.

**Comment by RoySCU** [comment]
Hi all, we have a potential solution for discussion. 

NDN-Lite maintains an **event queue** where forwarder, faces and application face (i.e., direct face) can post events and callbacks. Events queue handling API is exposed to users as a **loop()** and main program will block at queue handling. 

In this case, forwarder will post a _NOTIFY_TIMEOUT_ event to the queue, as the callback of timer expiry. Then queue handler/scheduler will execute _NOTIFY_TIMEOUT_ event callback inside **loop()**.

**Comment by Zhiyi-Zhang** [comment]
I can make some simple slides and present them to the NFD call to see people's comments. if you are available, you can do this also. The NFD call time is 2PM - 3PM PST.

**Comment by yoursunny** [comment]
> Events queue handling API is exposed to users as a **loop()** and main program will block at queue handling.

Where does "block at queue handling" occur?

**A** `loop()` invokes ready handlers, then return.
This is similar to Boost.Asio's [io\_context::poll](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/io_context/poll.html) and ndn-cpp's [face.processEvents()](https://github.com/named-data/ndn-cpp/blob/2ae85f9b7a8532c8a974234dd7878401ad62aded/include/ndn-cpp/face.hpp#L633-L646) and esp8266ndn's [Face::loop](https://github.com/yoursunny/esp8266ndn/blob/20abf173e4050649c816fc9a9246e3719d39205f/src/core/face.hpp#L101-L104).
Application needs to invoke `loop()` from time to time, but can perform other tasks on the same thread.

**B** `loop()` invokes handlers when they are ready and pauses if no handlers are ready, but does not return.
This is similar to Boost.Asio's [io\_context::run](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/io_context/poll.html) and ndn-cxx's [face.processEvents(0_ms, true)](https://github.com/named-data/ndn-cxx/blob/07115cc1065681beb9e57eededb7795a25c3b44e/ndn-cxx/face.hpp#L452-L457).
Application needs to use other threads to perform other tasks, and communicates with event queue thread via FIFOs.

> NDN-Lite maintains an **event queue** where forwarder, faces and application face (i.e., direct face) can post events and callbacks.

This statement makes me believe that you are adopting **B**. It would be problematic because NDN-Lite has to deal with multi-threading, and also forces application to be aware of threads because callbacks would be invoked on the event queue thread.
I'd recommend **A** so that NDN-Lite itself only deals with a single thread, just like most Arduino libraries. Let application deal with multi-threading if they choose to use them.

**Comment by RoySCU** [comment]
Your comments are correct, this is a **B** solution and actually comes from [ndn-riot](https://github.com/named-data-iot/ndn-riot/blob/master/ndn.c). In this case, application and event queue are in the same thread, and application won't perform any other tasks when `loop()`starts. In other words, application binds all needed callbacks before entering `loop()`.

About **A** solution,
> Application needs to invoke loop() from time to time, but can perform other tasks on the same thread.

Invoking `loop()` from time to time is good, but I am still wondering in what condition we invoke this and the cost of response time. For instance, If a timer fires and posts an event, how long time pass till this event get processed.

**Comment by yoursunny** [comment]
> application and event queue are in the same thread, and application won't perform any other tasks when `loop()`starts. application binds all needed callbacks before entering `loop()`.

This is unreasonable for many application whose main function is not communication.

> Invoking `loop()` from time to time is good, but I am still wondering in what condition we invoke this and the cost of response time. For instance, If a timer fires and posts an event, how long time pass till this event get processed.

`loop()` is invoked *unconditionally* in application's main loop.
It's similar to DPDK's [rte\_time\_manage](https://github.com/DPDK/dpdk/blob/c9e462d17b80394d3eaf8470198afaaa94a6c181/lib/librte_timer/rte_timer.h#L284-L295) function. See its Doxygen on the implication of invoking `loop()` more often or less often.

[PyNDN example invokes their `Face.processEvents` every 10ms](https://github.com/named-data/PyNDN2/blob/57b384797ce02b1785c3bf93e452957eff9ea938/examples/test_echo_consumer.py#L63).
If you need more accurate timing (e.g. for an advanced forwarding strategy), you can ask the application to invoke `loop()` more often.
